// <auto-generated />
using CandyReview.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CandyReview.Migrations
{
    [DbContext(typeof(CandyContext))]
    partial class CandyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CandyReview.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Chewy",
                            Name = "Swedish Fish"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Chewy",
                            Name = "Starburst"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Chocolate",
                            Name = "Heath Bar"
                        });
                });

            modelBuilder.Entity("CandyReview.Models.ReviewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Reviewer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Review",
                            Date = "july 32nd, 2020",
                            ProductId = 1,
                            Rating = 3,
                            Reviewer = "Corleeone"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Review",
                            Date = "January 1st, 1893",
                            ProductId = 1,
                            Rating = 2,
                            Reviewer = "Jake"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Review",
                            Date = "THE END TIMES",
                            ProductId = 2,
                            Rating = 1,
                            Reviewer = "Jackie Fredrickson"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Review",
                            Date = "33 BC",
                            ProductId = 2,
                            Rating = 47,
                            Reviewer = "Becky with the good hair"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Review",
                            Date = "Day 1",
                            ProductId = 3,
                            Rating = 0,
                            Reviewer = "Johnny Pearseed"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Review",
                            Date = "Decemberuary 4th, 3112",
                            ProductId = 3,
                            Rating = 5,
                            Reviewer = "Harriet Tubman"
                        });
                });

            modelBuilder.Entity("CandyReview.Models.ReviewModel", b =>
                {
                    b.HasOne("CandyReview.Models.ProductModel", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
